import { useState } from "react";
import { isModelEnabled, modelCatalog, modelFamilies } from "../core/catalog";
import type { Model } from "../types";
import { FamilyLogo } from "../components/FamilyLogo";

export function ModelCatalog({catalogVersion,familyApiKeys,onFamilyApiKey,onModelEnabled,onFamilyEnabled,onPricing}:{catalogVersion:number;familyApiKeys:Partial<Record<Model["family"],string>>;onFamilyApiKey:(family:Model["family"],key:string)=>void;onModelEnabled:(id:string,enabled:boolean)=>void;onFamilyEnabled:(family:Model["family"],enabled:boolean)=>void;onPricing:(id:string,input:number,output:number)=>void}) {
  void catalogVersion;
  const [apiKeyFamily,setApiKeyFamily]=useState<Model["family"]|null>(null);
  const [apiKeyDraft,setApiKeyDraft]=useState("");
  const openApiKeyModal=(family:Model["family"])=>{setApiKeyFamily(family);setApiKeyDraft(familyApiKeys[family]??"")};
  const closeApiKeyModal=()=>{setApiKeyFamily(null);setApiKeyDraft("")};
  const saveApiKey=()=>{if(!apiKeyFamily)return;onFamilyApiKey(apiKeyFamily,apiKeyDraft);closeApiKeyModal()};
  return <>{modelFamilies.map(family=>{
    const familyModels=modelCatalog.filter(model=>model.family===family);
    const enabledCount=familyModels.filter(isModelEnabled).length;
    const familyEnabled=enabledCount===familyModels.length;
    const apiKeyConfigured=Boolean(familyApiKeys[family]);
    return <section className="catalog-family" key={family}><div className="panelhead"><div className="family-head"><span className={`family-logo ${family.toLowerCase()}`}><FamilyLogo family={family} /></span><div><p className="eyebrow">Model family</p><h2>{family}</h2></div><button type="button" className={`api-key-button ${apiKeyConfigured?"configured":""}`} aria-label={`${family} API key settings`} title={family==="Local"?"Local models do not need an API key":apiKeyConfigured?"API key configured":"Add API key"} disabled={family==="Local"} onClick={()=>openApiKeyModal(family)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 10a4 4 0 1 1-1.2-2.8L22 7v4h-3v3h-3v3h-4l-2.1-2.1A4 4 0 0 1 14 10Zm-8 0a2 2 0 1 0 4 0 2 2 0 0 0-4 0Z" /></svg><span>{apiKeyConfigured?"Configured":"API key"}</span></button></div><label className="toggle-control"><input type="checkbox" checked={familyEnabled} onChange={event=>onFamilyEnabled(family,event.target.checked)} /><span className="switch-track" aria-hidden="true"><i /></span><span>{enabledCount}/{familyModels.length} enabled</span></label></div><div className="cards">{familyModels.map(model=>{
      const enabled=isModelEnabled(model);
      return <article className={`cluster-card model ${enabled?"":"disabled"}`} key={model.id}><div><span className="provider">{model.family_tier}</span><label className="toggle-control small"><input type="checkbox" checked={enabled} onChange={event=>onModelEnabled(model.id,event.target.checked)} /><span className="switch-track" aria-hidden="true"><i /></span><span>{enabled?"On":"Off"}</span></label></div><h2>{model.display_name}</h2><code>{model.id}</code><small className="pricing-source">{model.pricing_source}{model.pricing_source_model_id?` pricing: ${model.pricing_source_model_id}`:""}{model.pricing_updated_at?` · refreshed ${model.pricing_updated_at}`:""}</small><div className="pricing-editor compact"><label>Input / 1M tokens<input aria-label={`${model.display_name} input cost per 1M tokens`} type="number" min="0" step=".001" value={model.input_cost_per_1m} onChange={event=>onPricing(model.id,Number(event.target.value),model.output_cost_per_1m)} /></label><label>Output / 1M tokens<input aria-label={`${model.display_name} output cost per 1M tokens`} type="number" min="0" step=".001" value={model.output_cost_per_1m} onChange={event=>onPricing(model.id,model.input_cost_per_1m,Number(event.target.value))} /></label></div><dl><div><dt>Status</dt><dd>{enabled?"Considered":"Excluded"}</dd></div><div><dt>Default latency</dt><dd>{model.default_latency_ms}ms</dd></div><div><dt>Quality</dt><dd>{model.quality_tier}</dd></div></dl></article>;
    })}</div></section>;
  })}{apiKeyFamily&&<div className="key-modal-layer" role="presentation" onClick={event=>{if(event.target===event.currentTarget)closeApiKeyModal()}}><section className="key-modal" role="dialog" aria-modal="true" aria-label={`${apiKeyFamily} API key`}><div><p className="eyebrow">Live simulation key</p><h2>{apiKeyFamily} API key</h2><p>Stored locally in this session and used only when live simulations are enabled for this family.</p></div><label>API key<input autoFocus type="password" autoComplete="off" value={apiKeyDraft} placeholder={`Paste ${apiKeyFamily} API key`} onChange={event=>setApiKeyDraft(event.target.value)} /></label><div className="key-modal-actions"><button type="button" onClick={closeApiKeyModal}>Cancel</button><button type="button" className="primary" onClick={saveApiKey}>Save key</button></div></section></div>}</>;
}
