import { exportLiteLlm, exportOpenRouterConfig, exportPolicyJson, exportTypeScript, recommendPolicy } from "../core/recommendations";
import type { Model } from "../types";
import { download, money, pct } from "../lib/format";

function Comparison({ comparison }: { comparison: NonNullable<ReturnType<typeof recommendPolicy>["rules"][number]["comparison"]> }) {
  const rows = [
    { label: "Cost", before: money(comparison.cost.before), after: money(comparison.cost.after), delta: comparison.cost.delta_pct },
    { label: "Latency", before: `${comparison.latency_ms.before.toFixed(0)}ms`, after: `${comparison.latency_ms.after.toFixed(0)}ms`, delta: comparison.latency_ms.delta_pct },
    { label: "Quality", before: pct(comparison.quality.before * 100), after: pct(comparison.quality.after * 100), delta: comparison.quality.delta_pct },
  ];
  return <div className="comparison"><div className="comparison-head"><span>Projected impact</span><small>Before</small><small>After</small><small>Change</small></div>{rows.map(row=><div className="comparison-row" key={row.label}><b>{row.label}</b><span>{row.before}</span><strong>{row.after}</strong><em className={row.delta <= 0 && row.label !== "Quality" || row.delta >= 0 && row.label === "Quality" ? "good" : "warn"}>{row.delta > 0 ? "+" : ""}{pct(row.delta)}</em></div>)}</div>;
}

export function Recommendations({ policy,activeModels,traceCount }: { policy: ReturnType<typeof recommendPolicy>;activeModels:Model[];traceCount:number }) {
  if(!activeModels.length)return <section className="panel"><p className="eyebrow">Distinct Task routing</p><h2>No enabled models</h2><p>Enable at least one model in Model Catalog before generating recommendations.</p></section>;
  return <div className="recommendations-page"><section className="recommendation-controls panel"><div><p className="eyebrow">DeepSeek discovery routing</p><h2>Recommendation for you</h2><span className="recommendation-intro">We&apos;ve run your {traceCount.toLocaleString()} traces through DeepSeek models at no cost to you. Here are RouteLab&apos;s recommendations for where DeepSeek can reduce cost while preserving quality and latency guardrails.</span></div></section><section className="hero recommendation"><div><p className="eyebrow">Recommended DeepSeek policy savings</p><strong>{money(policy.estimated_monthly_savings_usd)}<small>/mo</small></strong><p>{money(policy.estimated_sample_savings_usd)} per uploaded sample × {policy.monthly_multiplier} monthly runs. {policy.risk_summary}</p></div><div className="export"><button onClick={()=>download("routelab-policy.json",exportPolicyJson(policy))}>Export JSON</button><button onClick={()=>download("openrouter-config.json",exportOpenRouterConfig(policy))}>OpenRouter config</button><button onClick={()=>download("litellm.yaml",exportLiteLlm(policy))}>LiteLLM config</button><button onClick={()=>download("router.ts",exportTypeScript(policy))}>TypeScript stub</button></div></section><div className="policy-note"><b>Monthly savings by Distinct Task</b><span>{policy.candidate_model_ids.length} DeepSeek candidate model{policy.candidate_model_ids.length===1?"":"s"} evaluated. Each card shows one Distinct Task’s contribution; rejected alternatives are not counted.</span></div><div className="cards recommendations-grid">{policy.rules.map(rule=><article className="cluster-card rule" key={rule.id}><div><span className={`risk ${rule.match.risk_level}`}>{rule.match.risk_level} risk</span><span className="strategy">{rule.strategy.type.replace("_"," ")}</span></div><div className="rule-title"><h2>{rule.name}</h2><div className={rule.estimated_monthly_savings_usd>0?"monthly-saving":"monthly-saving zero"}><small>Recommended monthly savings</small><b>{money(rule.estimated_monthly_savings_usd)}</b></div></div><p>{rule.rationale}</p>{rule.comparison&&<Comparison comparison={rule.comparison} />}{rule.rejected_alternative&&<div className="rejected-alternative"><div><span>Rejected alternative</span><b>{rule.rejected_alternative.model}</b><strong className="rejected-saving">Potential savings {money(rule.rejected_alternative.potential_monthly_savings_usd)}/mo</strong></div><p>{rule.rejected_alternative.reason}</p><Comparison comparison={rule.rejected_alternative.comparison} /></div>}{rule.strategy.type==="cascade"&&<div className="route"><b>{rule.strategy.primary_model}</b><span>evaluate → fallback</span><b>{rule.strategy.fallback_model}</b></div>}{rule.strategy.type==="direct"&&<div className="route"><span>Route directly to</span><b>{rule.strategy.model}</b></div>}</article>)}</div></div>;
}
