import { useState, type MouseEvent } from "react";
import type { MonthlyBucket } from "../core/time";

const chartColors=["#79bf49","#385c9a","#dc8b3f","#8a63b8","#cf5f75","#389892","#a6883d","#697f73"];

export function LineChart({title,series,metric,format}:{title:string;series:Array<{name:string;buckets:MonthlyBucket[]}>;metric:"calls"|"spend"|"tokens";format:(value:number)=>string}) {
  const [hoverIndex,setHoverIndex]=useState<number|null>(null);
  const allValues=series.flatMap(item=>item.buckets.map(bucket=>bucket[metric])); const high=Math.max(...allValues,1); const width=360; const height=130; const pad=18;
  const labels=series[0]?.buckets??[]; const total=allValues.reduce((sum,value)=>sum+value,0);
  const hoverX=hoverIndex===null?null:labels.length===1?width/2:pad+hoverIndex*(width-pad*2)/(labels.length-1);
  const handleMove=(event:MouseEvent<SVGSVGElement>)=>{if(!labels.length)return;const rect=event.currentTarget.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width*width;const index=labels.length===1?0:Math.round((x-pad)/(width-pad*2)*(labels.length-1));setHoverIndex(Math.max(0,Math.min(labels.length-1,index)))};
  return <article className="trend-chart" onMouseLeave={()=>setHoverIndex(null)}><div><b>{title}</b><strong>{format(total)}</strong></div><div className="chart-stage"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${title} monthly line chart`} onMouseMove={handleMove}><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} className="chart-axis" />{series.map((item,seriesIndex)=>{const points=item.buckets.map((bucket,index)=>({bucket,x:item.buckets.length===1?width/2:pad+index*(width-pad*2)/(item.buckets.length-1),y:height-pad-bucket[metric]/high*(height-pad*2)}));return <g key={item.name}><polyline points={points.map(point=>`${point.x},${point.y}`).join(" ")} className="chart-line" style={{stroke:chartColors[seriesIndex%chartColors.length]}} />{points.map((point,index)=><circle key={point.bucket.key} cx={point.x} cy={point.y} r={hoverIndex===index?"5":"3"} className="chart-point" style={{fill:chartColors[seriesIndex%chartColors.length]}} />)}</g>})}{hoverX!==null&&<line x1={hoverX} y1={pad} x2={hoverX} y2={height-pad} className="chart-hover-line" />}{labels.map((bucket,index)=><text key={bucket.key} x={labels.length===1?width/2:pad+index*(width-pad*2)/(labels.length-1)} y={height-3} textAnchor="middle">{bucket.label}</text>)}</svg>{hoverIndex!==null&&<div className="chart-tooltip" style={{left:`${hoverX!/width*100}%`}}><b>{labels[hoverIndex]?.label}</b>{series.map((item,index)=><span key={item.name}><i style={{background:chartColors[index%chartColors.length]}} /><em>{item.name}</em><strong>{format(item.buckets[hoverIndex]?.[metric]??0)}</strong></span>)}</div>}</div>{series.length>1&&<div className="chart-legend">{series.map((item,index)=><span key={item.name}><i style={{background:chartColors[index%chartColors.length]}} />{item.name}</span>)}</div>}</article>;
}
