import type { Trace, TraceJudgeResult } from "../types";
import type { SortDirection, TraceSortKey } from "../types/ui";
import { money, pct, preview, stripJudgeMarker } from "../lib/format";
import { SortHeader } from "./SortHeader";

export function TraceTable({ traces, judgeByTraceId, onSelect, sort, onSort }: { traces: Trace[]; judgeByTraceId?: Map<string, TraceJudgeResult>; onSelect?: (trace: Trace) => void; sort?: { key: TraceSortKey; direction: SortDirection }; onSort?: (key: TraceSortKey) => void }) {
  const header = (label: string, key: TraceSortKey) => sort && onSort ? <SortHeader label={label} sortKey={key} activeKey={sort.key} direction={sort.direction} onSort={onSort} /> : <th>{label}</th>;
  return <div className="tablewrap"><table><thead><tr>{header("Trace","trace")}{header("Model","model")}{header("Prompt","prompt")}{header("Response snapshot","response")}{header("LLM judge","judge")}{header("Tokens","tokens")}{header("Latency","latency")}{header("Cost","cost")}{header("Status","status")}</tr></thead><tbody>{traces.map((trace) => { const judge=judgeByTraceId?.get(trace.id); const response=stripJudgeMarker(trace.response_text); return <tr className={onSelect ? "trace-row" : ""} key={trace.id} tabIndex={onSelect ? 0 : undefined} onClick={() => onSelect?.(trace)} onKeyDown={(event) => { if (onSelect && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); onSelect(trace); } }}><td>{onSelect?<span className="trace-id-action"><code>{trace.id.slice(-15)}</code><button className="trace-details-button" aria-haspopup="dialog" aria-label={`View details for ${trace.id}`} onClick={(event)=>{event.stopPropagation();onSelect(trace)}}>View details</button></span>:<code>{trace.id.slice(-15)}</code>}</td><td>{trace.model}</td><td className="prompt">{trace.prompt_text}</td><td className="response-snapshot">{response || "No response captured"}</td><td className="judge-snapshot">{judge?<span className={`judge-score ${judge.passed?"pass":"fail"}`}>{pct(judge.score*100)}</span>:<span className="judge-score unknown">N/A</span>}<span className="judge-rationale">{judge?preview(judge.rationale,120):"No judge result"}</span></td><td>{trace.total_tokens}</td><td>{trace.latency_ms}ms</td><td>{money(trace.cost_usd ?? 0)}</td><td><span className={`status ${trace.status}`}>{trace.status}</span></td></tr>; })}</tbody></table></div>;
}
