import type { TaskType, Trace, TraceSpan } from "../types";

type SeedCategory={key:TaskType;prompt:string;response:string;metadata:Record<string,unknown>;spans?:TraceSpan[];tokens?:[number,number]};
const categories:SeedCategory[]=[
  {key:"summarization",prompt:"Summarize the meeting notes: launch moved to Friday, API bug fixed, onboarding email still blocked.",response:"The launch moved to Friday. The API bug is fixed. The onboarding email remains blocked.",metadata:{internal:true},tokens:[1200,180]},
  {key:"extraction",prompt:"Extract invoice_id, due_date, total, and currency from: Invoice INV-2048 is due 2026-07-01 for USD 418.25.",response:'{"invoice_id":"INV-2048","due_date":"2026-07-01","total":418.25,"currency":"USD"}',metadata:{expected_fields:["invoice_id","due_date","total","currency"],internal:true},tokens:[700,90]},
  {key:"classification_tagging",prompt:"Classify this support ticket intent, priority, and sentiment: I was charged twice after upgrading yesterday.",response:"intent=billing_dispute; priority=high; sentiment=frustrated",metadata:{labels:["intent","priority","sentiment"],internal:true},tokens:[600,40]},
  {key:"question_answering",prompt:"Answer the question: what is the difference between API latency and throughput?",response:"Latency is time per request. Throughput is the number of requests handled per unit time.",metadata:{internal:true},tokens:[800,130]},
  {key:"rag_grounded_answers",prompt:"Using the retrieved refund policy excerpt, answer whether an annual-plan customer can get a refund and cite the policy.",response:"Yes, if the annual plan was purchased within 30 days, according to the retrieved refund policy [1].",metadata:{retrieved_context:"Annual plans can be refunded within 30 days.",citations_required:true},spans:[{id:"retrieval",type:"retriever",name:"policy search"}],tokens:[3200,450]},
  {key:"customer_support_responses",prompt:"Draft a customer-facing reply explaining how to reset a password.",response:"You can reset your password from Account Settings > Security. I can also send a reset link if needed.",metadata:{channel:"customer-facing support chat",policy:"account access policy"},tokens:[900,180]},
  {key:"policy_compliance_reasoning",prompt:"Check whether an outbound email complies with the policy requiring an unsubscribe link and no misleading subject lines.",response:"Non-compliant: it lacks an unsubscribe link. The subject line is acceptable.",metadata:{policy:"marketing compliance policy",internal:true},tokens:[1800,260]},
  {key:"code_generation",prompt:"Developer tooling: write a TypeScript retry helper with exponential backoff.",response:"```ts\nexport async function retry<T>(fn:()=>Promise<T>, attempts=3){let last;for(let i=0;i<attempts;i++){try{return await fn()}catch(err){last=err;await new Promise(r=>setTimeout(r,100*2**i))}}throw last}\n```",metadata:{internal:true},tokens:[1800,500]},
  {key:"code_review_debugging",prompt:"Developer tooling: review this PR diff and find severe bugs in the API handler.",response:"The handler writes the order before checking idempotency, so retries can create duplicate orders.",metadata:{internal:true},tokens:[2600,550]},
  {key:"sql_data_query_generation",prompt:"Internal analytics: write SQL to calculate weekly active users from events(user_id, created_at).",response:"SELECT date_trunc('week', created_at) AS week, count(DISTINCT user_id) AS wau FROM events GROUP BY 1 ORDER BY 1;",metadata:{internal:true},tokens:[1200,180]},
  {key:"data_analysis_insight_generation",prompt:"Analyze dashboard metrics: activation rose 8%, retention fell 3%, and support tickets doubled.",response:"Activation improved, but retention and ticket volume suggest onboarding quality or reliability may have regressed.",metadata:{internal:true},tokens:[1400,220]},
  {key:"writing_editing",prompt:"Rewrite this update to be clearer and shorter: We are experiencing some delay on account of a dependency.",response:"We are delayed because a dependency is not ready yet.",metadata:{internal:true},tokens:[800,120]},
  {key:"sales_marketing_content",prompt:"Write three outbound email subject lines for CFOs about reducing LLM spend.",response:"1. Cut LLM spend without slowing teams\n2. Find hidden AI routing waste\n3. Lower model costs with eval-backed routing",metadata:{internal:true,campaign:"finance buyers"},tokens:[900,160]},
  {key:"translation_localization",prompt:"Translate to Spanish for a friendly support email: Your refund request is under review.",response:"Tu solicitud de reembolso está en revisión.",metadata:{source_locale:"en-US",target_locale:"es-ES"},tokens:[600,80]},
  {key:"document_review_legal_analysis",prompt:"Review this contract clause for unusual termination obligations and legal risk.",response:"The clause allows termination for convenience but requires 60 days notice and payment of committed fees.",metadata:{document_type:"contract",internal:true},tokens:[2600,420]},
  {key:"planning_strategy_recommendations",prompt:"Create a 30-day rollout plan for model routing changes across support traffic.",response:"Week 1 baseline evals; week 2 low-risk shadow routing; week 3 support pilot; week 4 monitored rollout with rollback thresholds.",metadata:{internal:true},tokens:[1700,260]},
  {key:"tool_use_function_calling",prompt:"Use the inventory API and shipping calculator to confirm whether order SO-781 can ship today.",response:'{"order_id":"SO-781","inventory_available":true,"shipping_window":"today"}',metadata:{internal:true,workflow:"operations"},spans:[{id:"inventory",type:"tool",name:"inventory API"},{id:"shipping",type:"function",name:"shipping calculator"}],tokens:[1800,220]},
  {key:"agentic_workflow_execution",prompt:"Research competitors, draft a positioning brief, create follow-up tasks, and report status.",response:"Completed: gathered three competitor notes, drafted positioning themes, created launch tasks, and flagged pricing as unresolved.",metadata:{internal:true,workflow:"research_plan_act_verify"},spans:[{id:"agent",type:"agent",name:"market research agent"},{id:"search",type:"tool",name:"web research"},{id:"tasks",type:"function",name:"task creator"}],tokens:[3600,420]},
  {key:"moderation_safety_review",prompt:"Review this user message for harassment and self-harm risk: 'You are worthless and should disappear.'",response:"harassment=true; self_harm_reference=false; action=block_or_warn",metadata:{policy:"safety moderation policy"},tokens:[1000,120]},
  {key:"multimodal_document_image_understanding",prompt:"Interpret this screenshot of a checkout error and identify the likely failed field.",response:"The card ZIP field is highlighted, so the likely failure is postal code validation.",metadata:{input_modality:"screenshot",internal:true},tokens:[2200,260]},
];
export const DISTINCT_TASK_SEED_COUNT=60;
export function createDistinctTaskSeedTraces():Trace[]{
  return categories.flatMap((category,categoryIndex)=>Array.from({length:3},(_,index)=>{
    const [input,output]=category.tokens??[1000,200]; const suffix=index+1;
    return {id:`task_${category.key}_${suffix}`,timestamp:new Date(Date.UTC(2026,5,1+categoryIndex)).toISOString(),provider:"openai",model:"gpt-5.4",messages:[{role:"user",content:`${category.prompt} Example ${suffix}`}],prompt_text:`${category.prompt} Example ${suffix}`,response_text:category.response,input_tokens:input,output_tokens:output,total_tokens:input+output,latency_ms:800+categoryIndex*40,cost_usd:.05+categoryIndex*.01,status:"success",source:"json",spans:category.spans,metadata:{...category.metadata,task_type:category.key}};
  }));
}
