import type { TaskType, Trace, TraceSpan } from "../types";

type SeedCategory={key:TaskType;prompt:string;response:string;metadata:Record<string,unknown>;spans?:TraceSpan[];tokens?:[number,number]};
const categories:SeedCategory[]=[
  {key:"summarization",prompt:"As an AI customer support agent, summarize this escalated support thread: customer cannot export data, billing is current, engineering says the export job timed out.",response:"The customer cannot export data despite active billing. Engineering traced the issue to an export job timeout.",metadata:{internal:true},tokens:[1200,180]},
  {key:"extraction",prompt:"As an AI customer support agent, extract invoice_id, due_date, total, and currency from the customer's billing attachment: Invoice INV-2048 is due 2026-07-01 for USD 418.25.",response:'{"invoice_id":"INV-2048","due_date":"2026-07-01","total":418.25,"currency":"USD"}',metadata:{expected_fields:["invoice_id","due_date","total","currency"],internal:true},tokens:[700,90]},
  {key:"classification_tagging",prompt:"As an AI customer support agent, classify this support ticket intent, priority, and sentiment: I was charged twice after upgrading yesterday.",response:"intent=billing_dispute; priority=high; sentiment=frustrated",metadata:{labels:["intent","priority","sentiment"],internal:true},tokens:[600,40]},
  {key:"question_answering",prompt:"As an AI customer support agent, answer the customer's question: what is the difference between API latency and throughput?",response:"Latency is time per request. Throughput is the number of requests handled per unit time.",metadata:{internal:true},tokens:[800,130]},
  {key:"rag_grounded_answers",prompt:"As an AI customer support agent, using the retrieved refund policy excerpt, answer whether an annual-plan customer can get a refund and cite the policy.",response:"Yes, if the annual plan was purchased within 30 days, according to the retrieved refund policy [1].",metadata:{retrieved_context:"Annual plans can be refunded within 30 days.",citations_required:true},spans:[{id:"retrieval",type:"retriever",name:"policy search"}],tokens:[3200,450]},
  {key:"customer_support_responses",prompt:"As an AI customer support agent, draft a customer-facing reply explaining how to reset a password.",response:"You can reset your password from Account Settings > Security. I can also send a reset link if needed.",metadata:{channel:"customer-facing support chat",policy:"account access policy"},tokens:[900,180]},
  {key:"policy_compliance_reasoning",prompt:"As an AI customer support agent, check whether this customer reply complies with the refund policy and avoids promising approval before review.",response:"Compliant if it says the team will review eligibility; non-compliant if it guarantees a refund before verification.",metadata:{policy:"refund compliance policy",internal:true},tokens:[1800,260]},
  {key:"code_generation",prompt:"As an AI customer support agent, write a TypeScript helper that retries a failed support-ticket lookup with exponential backoff.",response:"```ts\nexport async function retry<T>(fn:()=>Promise<T>, attempts=3){let last;for(let i=0;i<attempts;i++){try{return await fn()}catch(err){last=err;await new Promise(r=>setTimeout(r,100*2**i))}}throw last}\n```",metadata:{internal:true},tokens:[1800,500]},
  {key:"code_review_debugging",prompt:"As an AI customer support agent, review this support automation diff and find severe bugs in the refund API handler.",response:"The handler writes the credit before checking idempotency, so retries can create duplicate credits.",metadata:{internal:true},tokens:[2600,550]},
  {key:"sql_data_query_generation",prompt:"As an AI customer support agent, write SQL to calculate weekly support tickets by issue category from tickets(category, created_at).",response:"SELECT date_trunc('week', created_at) AS week, category, count(*) AS ticket_count FROM tickets GROUP BY 1, 2 ORDER BY 1, 2;",metadata:{internal:true},tokens:[1200,180]},
  {key:"data_analysis_insight_generation",prompt:"As an AI customer support agent, analyze support metrics: password-reset tickets fell 8%, refund tickets rose 3%, and SLA breaches doubled.",response:"Password-reset volume improved, but refund volume and SLA breaches indicate billing friction or staffing issues may have regressed.",metadata:{internal:true},tokens:[1400,220]},
  {key:"writing_editing",prompt:"As an AI customer support agent, rewrite this customer update to be clearer and shorter: We are experiencing some delay on account of a dependency.",response:"We are delayed because a dependency is not ready yet.",metadata:{internal:true},tokens:[800,120]},
  {key:"sales_marketing_content",prompt:"As an AI customer support agent, write three proactive support email subject lines for customers who may exceed plan limits.",response:"1. Heads up: your usage is nearing its limit\n2. Avoid overages with a quick plan check\n3. Review your usage before the next billing cycle",metadata:{internal:true,campaign:"customer success"},tokens:[900,160]},
  {key:"translation_localization",prompt:"As an AI customer support agent, translate to Spanish for a friendly support email: Your refund request is under review.",response:"Tu solicitud de reembolso está en revisión.",metadata:{source_locale:"en-US",target_locale:"es-ES"},tokens:[600,80]},
  {key:"document_review_legal_analysis",prompt:"As an AI customer support agent, review this enterprise support agreement clause for unusual termination obligations before escalating to legal.",response:"The clause allows termination for convenience but requires 60 days notice and payment of committed fees.",metadata:{document_type:"support agreement",internal:true},tokens:[2600,420]},
  {key:"planning_strategy_recommendations",prompt:"As an AI customer support agent, create a 30-day rollout plan for new refund macros across support traffic.",response:"Week 1 baseline quality review; week 2 low-risk shadow use; week 3 support pilot; week 4 monitored rollout with rollback thresholds.",metadata:{internal:true},tokens:[1700,260]},
  {key:"tool_use_function_calling",prompt:"As an AI customer support agent, use the order API and shipping calculator to confirm whether order SO-781 can ship today.",response:'{"order_id":"SO-781","inventory_available":true,"shipping_window":"today"}',metadata:{internal:true,workflow:"support operations"},spans:[{id:"inventory",type:"tool",name:"order API"},{id:"shipping",type:"function",name:"shipping calculator"}],tokens:[1800,220]},
  {key:"agentic_workflow_execution",prompt:"As an AI customer support agent, research the customer's outage history, draft an escalation brief, create follow-up tasks, and report status.",response:"Completed: reviewed outage history, drafted escalation themes, created follow-up tasks, and flagged SLA eligibility as unresolved.",metadata:{internal:true,workflow:"research_plan_act_verify"},spans:[{id:"agent",type:"agent",name:"support escalation agent"},{id:"search",type:"tool",name:"ticket history search"},{id:"tasks",type:"function",name:"task creator"}],tokens:[3600,420]},
  {key:"moderation_safety_review",prompt:"As an AI customer support agent, review this customer message for harassment and self-harm risk: 'You are worthless and should disappear.'",response:"harassment=true; self_harm_reference=false; action=block_or_warn",metadata:{policy:"safety moderation policy"},tokens:[1000,120]},
  {key:"multimodal_document_image_understanding",prompt:"As an AI customer support agent, interpret this customer screenshot of a checkout error and identify the likely failed field.",response:"The card ZIP field is highlighted, so the likely failure is postal code validation.",metadata:{input_modality:"screenshot",internal:true},tokens:[2200,260]},
];
export const DISTINCT_TASK_SEED_COUNT=60;
export function createDistinctTaskSeedTraces():Trace[]{
  return categories.flatMap((category,categoryIndex)=>Array.from({length:3},(_,index)=>{
    const [input,output]=category.tokens??[1000,200]; const suffix=index+1;
    return {id:`task_${category.key}_${suffix}`,timestamp:new Date(Date.UTC(2026,5,1+categoryIndex)).toISOString(),provider:"openai",model:"gpt-5.4",messages:[{role:"user",content:`${category.prompt} Example ${suffix}`}],prompt_text:`${category.prompt} Example ${suffix}`,response_text:category.response,input_tokens:input,output_tokens:output,total_tokens:input+output,latency_ms:800+categoryIndex*40,cost_usd:.05+categoryIndex*.01,status:"success",source:"json",spans:category.spans,metadata:{...category.metadata,task_type:category.key,domain:"customer_support"}};
  }));
}
