import type { EvalPlan, EvalRecommendation, EvalType, DistinctTaskBucket } from "../types";

const recommendation=(eval_type:EvalType,priority:EvalRecommendation["priority"],reason:string,suggested_config?:Record<string,unknown>):EvalRecommendation=>({eval_type,priority,reason,suggested_config});
export interface EvalPlanGenerator { generate(bucket:DistinctTaskBucket):EvalPlan }
export class DistinctTaskEvalPlanGenerator implements EvalPlanGenerator {
  generate(bucket:DistinctTaskBucket):EvalPlan {
    const s=bucket.task; const required:EvalRecommendation[]=[]; const recommended:EvalRecommendation[]=[]; const optional:EvalRecommendation[]=[];
    const add=(list:EvalRecommendation[],type:EvalType,reason:string,config?:Record<string,unknown>)=>{
      const existing=[...required,...recommended,...optional].find(item=>item.eval_type===type);
      if(existing&&list!==required)return;
      if(existing){const recommendedIndex=recommended.findIndex(item=>item.eval_type===type);const optionalIndex=optional.findIndex(item=>item.eval_type===type);if(recommendedIndex>=0)recommended.splice(recommendedIndex,1);if(optionalIndex>=0)optional.splice(optionalIndex,1)}
      list.push(recommendation(type,list===required?"required":list===recommended?"recommended":"optional",reason,config));
    };
    let rule="rubric_score >= 0.85 AND critical_failure_rate <= 0.01";
    if(s.task_type==="extraction"&&s.output_format==="json"){add(required,"json_schema_validation","Structured extraction must remain parseable.");add(required,"field_level_exact_match","Critical extracted fields should match references.");add(recommended,"required_facts_check","Verify required fields are present.");add(recommended,"hallucination_check","Reject invented fields.");rule="json_schema_pass_rate >= 0.99 AND critical_field_accuracy >= 0.98"}
    if(s.task_type==="classification_tagging"){add(required,"classification_accuracy","Measure label correctness.");add(recommended,"confusion_matrix","Expose class-specific regressions.");rule="classification_accuracy >= 0.95 AND no critical class recall below 0.90"}
    if(s.task_type==="rag_grounded_answers"||["retrieval_augmented","source_citation_required"].includes(s.grounding_requirement)){add(required,"groundedness_judge","Answers must be supported by retrieved evidence.");if(s.grounding_requirement==="source_citation_required")add(required,"citation_accuracy","Citations must support claims.");add(required,"hallucination_check","Unsupported claims are unsafe.");add(recommended,"required_facts_check","Verify essential facts.");add(recommended,"pairwise_judge_against_baseline","Compare against current answer quality.");rule="groundedness_score >= 0.90 AND hallucination_rate <= 0.02"}
    if(s.task_type==="customer_support_responses"){if(s.grounding_requirement==="policy_grounded")add(required,"policy_compliance_judge","Support answer must follow policy.");add(required,"groundedness_judge","Support claims need a reliable basis.");add(required,"required_facts_check","Ensure the customer receives required facts.");add(recommended,"human_review_sample","Sample customer-facing answers.");add(recommended,"pairwise_judge_against_baseline","Compare tone and helpfulness.");rule="policy_compliance >= 0.95 AND critical_failure_rate <= 0.005"}
    if(s.task_type==="code_generation"){add(required,"unit_tests","Generated code must pass behavior tests.");add(required,"compile_check","Generated code must compile.");add(recommended,"rubric_judge","Assess maintainability and approach.");add(recommended,"pairwise_judge_against_baseline","Compare code quality.");rule="tests_pass_rate >= 0.95 AND compile_pass_rate >= 0.99"}
    if(s.task_type==="code_review_debugging"){add(required,"rubric_judge","Assess review completeness and severity.");add(required,"pairwise_judge_against_baseline","Compare review usefulness.");add(recommended,"human_review_sample","Sample missed issues.");add(recommended,"required_facts_check","Verify referenced issues exist.");rule="review_quality_score >= 0.85 AND missed_severe_issue_rate <= 0.02"}
    if(s.task_type==="sql_data_query_generation"){add(required,"sql_parse","SQL must parse.");add(required,"sql_execution","SQL must execute successfully.");add(recommended,"field_level_exact_match","Compare result shape or expected results.");add(recommended,"safety_policy_check","Reject destructive or unsafe queries.");rule="sql_parse_rate >= 0.99 AND execution_success_rate >= 0.95"}
    if(s.task_type==="summarization"){add(required,"summarization_fidelity_judge","Summary must faithfully represent the source.");add(required,"hallucination_check","Summary must not invent facts.");add(recommended,"omission_check","Detect missing critical facts.");add(recommended,"pairwise_judge_against_baseline","Compare usefulness.");rule="fidelity_score >= 0.90 AND hallucination_rate <= 0.02"}
    if(s.tool_use !== "none"){add(required,"tool_call_validity","Tool selection and call shape must be valid.");add(required,"tool_argument_correctness","Tool arguments must match the request.");add(recommended,"business_outcome_check","Verify the workflow reaches the intended outcome.")}
    if(s.temporal_context!=="single_turn"){add(required,"context_retention","Verify facts and constraints survive across conversation turns.");add(required,"instruction_adherence","Detect instruction drift and conflicting-turn failures.");}
    if(["recovered_failure","failed"].includes(s.tool_use)){add(required,"tool_error_recovery","Evaluate whether tool failures are detected, communicated, and recovered safely.");add(required,"business_outcome_check","Verify the workflow still reaches an acceptable outcome after tool failure.");}
    if(s.output_uncertainty==="low"&&bucket.risk_level!=="low"){add(required,"uncertainty_calibration","Confident consequential answers must be correct and appropriately calibrated.");add(recommended,"human_review_sample","Review confident answers for dangerous silent failures.");}
    if(s.output_uncertainty==="high"){add(recommended,"uncertainty_calibration","Check whether expressed uncertainty matches actual answer quality.");}
    if(!required.length){add(required,"rubric_judge","Use a task-specific quality rubric.");add(recommended,"pairwise_judge_against_baseline","Compare against the current model.");add(optional,"human_review_sample","Calibrate the automated rubric.")}
    const human=bucket.risk_level==="high"||s.tool_use==="failed"||bucket.low_confidence_count>0;
    if(bucket.risk_level==="high"){add(required,"human_review_sample","High-risk buckets require human review.");add(required,"rubric_judge","Apply a strict domain rubric.");add(required,"safety_policy_check","Check high-risk safety requirements.");if(s.grounding_requirement!=="none")add(required,"groundedness_judge","High-risk grounded claims require evidence.");rule="critical_failure_rate <= 0.001 AND human_review_pass_rate >= 0.98"}
    else if(human)add(required,"human_review_sample","Low-confidence tasks require review before routing.");
    add(optional,"business_outcome_check","Connect eval scores to downstream outcomes when available.");
    const minimumSample=Math.max(bucket.risk_level==="high"?100:bucket.customer_facing?50:30,s.complexity==="high"?75:s.complexity==="medium"?50:30,s.temporal_context==="late_multi_turn"?75:30,s.tool_use==="failed"?100:30);
    return {bucket_id:bucket.bucket_id,task:s,plan_name:`Eval plan for ${bucket.bucket_name}`,confidence:bucket.avg_confidence,required_evals:required,recommended_evals:recommended,optional_evals:optional,human_review_required:human,minimum_sample_size:minimumSample,route_readiness_rule:rule,notes:[`Generated from an exact Distinct Task bucket with ${bucket.trace_count.toLocaleString()} traces.`,`Complexity is ${s.complexity}; input/output size is one contributing signal, alongside semantic density, reasoning, tools, grounding, and historical difficulty.`,`Temporal context: ${s.temporal_context}; tool use: ${s.tool_use}; expressed uncertainty: ${s.output_uncertainty}.`,human?"Human review is required before routing changes.":"Automated evidence can establish route readiness."]};
  }
}
export const generateEvalPlans=(buckets:DistinctTaskBucket[],generator:EvalPlanGenerator=new DistinctTaskEvalPlanGenerator())=>new Map(buckets.map(bucket=>[bucket.bucket_id,generator.generate(bucket)]));
